[package]
name = "site-storage"
version = "0.1.0"
authors = ["DieMyst <dmitry.shakhtarin@fluence.ai>"]
edition = "2018"

[[bin]]
name = "site-storage"
path = "src/main.rs"

[dependencies]
fluence = { git = "https://github.com/fluencelabs/rust-sdk", features = ["logger"] }
anyhow = "1.0.31"
log = "0.4.8"


