modules_dir = "wasm/artifacts/modules/"

[[module]]
    name = "wasm_local_storage"
    logger_enabled = true

    [module.wasi]
    preopened_files = ["./wasm/artifacts"]
    mapped_dirs = { "test" = "./wasm/artifacts" }

[[module]]
    name = "wasm_curl"
    logger_enabled = true

    [module.imports]
    curl = "/usr/bin/curl"

[[module]]
    name = "site-storage"
    logger_enabled = true


