[package]
name = "marine-it-generator"
description = "Fluence Marine interface types generator"
version = "0.9.4"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = { workspace = true }

[lib]
name = "marine_it_generator"
path = "src/lib.rs"

[dependencies]
marine-it-parser = { path = "../it-parser", version = "0.11.0" }
marine-macro-impl = "0.7.1"

wasmer-it = { workspace = true }
it-lilo = { workspace = true}

thiserror = "1.0.34"
walrus = "0.19.0"
once_cell = "1.14.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
