[package]
name = "marine-it-generator"
description = "Fluence Marine interface types generator"
version = "0.6.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_it_generator"
path = "src/lib.rs"

[dependencies]
marine-it-parser = { path = "../it-parser", version = "0.7.0"}
marine-macro-impl = "0.6.10"

wasmer-it = { package = "wasmer-interface-types-fl", version = "0.22.0" }
it-lilo = "0.3.0"

thiserror = "1.0.24"
walrus = "0.18.0"
once_cell = "1.4.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.56"
cargo_toml = "0.8.1"
