[package]
name = "marine-it-generator"
description = "Fluence Marine interface types generator"
version = "0.10.2"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2021"

[lib]
name = "marine_it_generator"
path = "src/lib.rs"

[dependencies]
marine-it-parser = { path = "../it-parser", version = "0.12.2" }
marine-macro-impl = "0.7.1"

wasmer-it = { package = "wasmer-interface-types-fl", version = "0.26.1" }
it-lilo = "0.5.1"

thiserror = "1.0.37"
walrus = "0.19.0"
once_cell = "1.16.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
