[package]
name = "marine-runtime"
description = "The Fluence Wasm Runtime"
version = "0.23.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine"
path = "src/lib.rs"

[dependencies]
marine-core = { path = "../core", version = "0.18.0" }
marine-module-interface = { path = "../crates/module-interface", version = "0.6.0" }
marine-utils = { path = "../crates/utils", version = "0.4.0" }
marine-rs-sdk-main = { version = "0.7.1", features = ["logger"] }
marine-rs-sdk = { version = "0.7.1", features = ["logger"] }
it-json-serde = { path = "../crates/it-json-serde", version = "0.3.4" }

#wasmer-wasi = { package = "wasmer-wasi-fl", version = "0.17.1" }
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.24.1" }
marine-wasm-backend-traits = { path = "../crates/wasm-backend-traits", version = "0.1.0"}
it-memory-traits = "0.1.0"

toml = "0.5.9"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_derive = "1.0.144"
serde_with = "2.0.0"
bytesize = {version = "1.1.0", features = ["serde"]}
itertools = "0.10.3"
log = "0.4.17"
safe-transmute = "0.11.2"
thiserror = "1.0.34"

[dev-dependencies]
once_cell = "1.14.0"
env_logger = "0.9.0"
pretty_assertions = "1.3.0"
marine-wasmer-backend = { path = "../crates/wasmer-backend", version = "0.1.0"}

[features]
raw-module-api = []
