[package]
name = "marine-runtime"
description = "The Fluence Wasm Runtime"
version = "0.20.2"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine"
path = "src/lib.rs"

[dependencies]
marine-core = { path = "../core", version = "0.16.2" }
marine-module-interface = { path = "../crates/module-interface", version = "0.4.2" }
marine-utils = { path = "../crates/utils", version = "0.4.0" }
marine-rs-sdk-main = { version = "0.7.0", features = ["logger"] }
marine-rs-sdk = { version = "0.7.0", features = ["logger"] }
it-json-serde = { path = "../crates/it-json-serde", version = "0.3.2" }

wasmer-runtime = { package = "wasmer-runtime-fl", version = "=0.17.1" }
# dynamicfunc-fat-closures allows using state inside DynamicFunc
wasmer-core = { package = "wasmer-runtime-core-fl", version = "=0.17.1", features = ["dynamicfunc-fat-closures"] }
wasmer-wasi = { package = "wasmer-wasi-fl", version = "0.17.1" }
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.23.1" }

toml = "0.5.9"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_derive = "1.0.144"
serde_with = "1.14.0"
bytesize = {version = "1.1.0", features = ["serde"]}
itertools = "0.10.3"
log = "0.4.17"
safe-transmute = "0.11.2"
thiserror = "1.0.33"

[dev-dependencies]
once_cell = "1.13.1"
env_logger = "0.9.0"
pretty_assertions = "1.3.0"

[features]
raw-module-api = []
