[package]
name = "marine-runtime"
description = "The Fluence Wasm Runtime"
version = "0.26.3"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2021"

[lib]
name = "marine"
path = "src/lib.rs"

[dependencies]
marine-core = { path = "../core", version = "0.20.3" }
marine-module-interface = { path = "../crates/module-interface", version = "0.7.1" }
marine-utils = { path = "../crates/utils", version = "0.5.0" }
marine-rs-sdk-main = { version = "0.7.1", features = ["logger"] }
marine-rs-sdk = { version = "0.7.1", features = ["logger"] }
it-json-serde = { path = "../crates/it-json-serde", version = "0.4.1" }
marine-wasm-backend-traits = { path = "../crates/wasm-backend-traits", version = "0.2.1"}
marine-wasmtime-backend = { path = "../crates/wasmtime-backend", version = "0.2.2"}

wasmer-it = { package = "wasmer-interface-types-fl", version = "0.26.1" }
it-memory-traits = "0.4.0"

toml = "0.5.9"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
serde_derive = "1.0.147"
serde_with = "2.1.0"
bytesize = {version = "1.1.0", features = ["serde"]}
itertools = "0.10.5"
log = "0.4.17"
safe-transmute = "0.11.2"
thiserror = "1.0.37"
parking_lot = "0.12.1"

[dev-dependencies]
once_cell = "1.16.0"
env_logger = "0.9.3"
pretty_assertions = "1.3.0"

[features]
raw-module-api = []
