[package]
name = "marine-wasm-backend-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"

wasmer-it = { workspace = true }
it-memory-traits = { workspace = true }

tuple_list = "0.1.0"
paste = "1.0.11"