[package]
name = "marine-wasm-backend-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.24"
anyhow = "1.0.68"

wasmer-it = { workspace = true }
it-memory-traits = { workspace = true }

tuple_list = "0.1.0"
paste = "1.0.9"
