modules_dir = "artifacts/wasm_modules"

[[module]]
    name = "effector"
    mem_pages_count = 1
    logger_enabled = true

[[module]]
    name = "pure"
    mem_pages_count = 1
    logger_enabled = true
