modules_dir = "artifacts/"

[[module]]
    name = "records_effector_old"
    mem_pages_count = 1
    logger_enabled = true

[[module]]
    name = "records_pure_old"
    mem_pages_count = 1
    logger_enabled = true
