modules_dir = "artifacts/wasm_modules"

[[module]]
    name = "effector.wasm"
    mem_pages_count = 1
    logger_enabled = true

[[module]]
    name = "pure.wasm"
    mem_pages_count = 1
    logger_enabled = true
