core_modules_dir = "wasm/artifacts/wasm_modules"

[[core_module]]
    name = "effector.wasm"
    mem_pages_count = 1
    logger_enabled = true

[[core_module]]
    name = "pure.wasm"
    mem_pages_count = 1
    logger_enabled = true
