[package]
name = "record-effector"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "records_effector"
path = "src/main.rs"

[dependencies]
#fluence = { git = "https://github.com/fluencelabs/rust-sdk" }
fluence = { path = "/Users/mike/dev/work/fluence/wasm/rust-sdk/fluence" }
test-record = { path = "../test-record" }
