[package]
name = "record-effector"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[[bin]]
name = "effector"
path = "src/main.rs"

[dependencies]
fluence = { path = "/Users/mike/dev/work/fluence/wasm/rust-sdk", branch = "record_support" }
test-record = { path = "../test-record" }