[package]
name = "ipfs-pure"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = { workspace = true }
publish = false

[[bin]]
name = "ipfs_pure"
path = "src/main.rs"

[dependencies]
marine-rs-sdk ={ version = "0.7.0", features = ["logger"] }
log = "0.4.14"
