[package]
name = "ipfs-pure"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "ipfs_pure"
path = "src/main.rs"

[dependencies]
#fluence = { version = "=0.2.18", features = ["logger"]}
fluence = { git = "https://github.com/fluencelabs/rust-sdk", branch = "mounted_binary_result", features = ["logger"] }
log = "0.4.11"
