[workspace]
members = [
    "core",
    "core/tests/wasm_tests/lilo_after_2gb",
    "crates/fluence-app-service",
    "crates/it-generator",
    "crates/it-interfaces",
    "crates/it-parser",
    "crates/it-json-serde",
    "crates/min-it-version",
    "crates/module-info-parser",
    "crates/module-interface",
    "crates/utils",
    "examples/call_parameters",
    "examples/failing",
    "examples/greeting",
    "examples/greeting_record",
    "examples/ipfs-node/effector",
    "examples/ipfs-node/pure",
    "examples/motivational-example/donkey",
    "examples/motivational-example/shrek",
    "examples/records/effector",
    "examples/records/pure",
    "examples/records/test-record",
    "examples/sqlite",
    "examples/url-downloader/curl_adapter",
    "examples/url-downloader/facade",
    "examples/url-downloader/local_storage",
    "examples/multiservice_marine_test",
    "examples/multiservice_marine_test/consumer",
    "examples/multiservice_marine_test/producer",
    "examples/build_rs",
    "marine",
    "marine/tests/wasm_tests/arguments_passing",
    "marine/tests/wasm_tests/arrays_passing",
    "marine/tests/wasm_tests/records_passing",
    "marine/tests/wasm_tests/wasi",
    "marine-js",
    "tools/cli",
    "tools/repl",
]

[patch.crates-io]
fluence-it-types = {version = "0.3.2", git = "https://github.com/fluencelabs/interface-types", branch = "renovate/wast-50.x"}

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
