[workspace]
members = [
    "core",
    "core/tests/wasm_tests/lilo_after_2gb",
    "crates/fluence-app-service",
    "crates/it-generator",
    "crates/it-interfaces",
    "crates/it-parser",
    "crates/it-json-serde",
    "crates/js-backend",
    "crates/min-it-version",
    "crates/module-info-parser",
    "crates/module-interface",
    "crates/wasm-backend-traits",
    "crates/wasmer-backend",
    "crates/marine-wasmtime-backend",
    "crates/utils",
    "examples/call_parameters",
    "examples/failing",
    "examples/greeting",
    "examples/greeting_record",
    "examples/ipfs-node/effector",
    "examples/ipfs-node/pure",
    "examples/motivational-example/donkey",
    "examples/motivational-example/shrek",
    "examples/records/effector",
    "examples/records/pure",
    "examples/records/test-record",
    "examples/sqlite",
    "examples/url-downloader/curl_adapter",
    "examples/url-downloader/facade",
    "examples/url-downloader/local_storage",
    "examples/multiservice_marine_test",
    "examples/multiservice_marine_test/consumer",
    "examples/multiservice_marine_test/producer",
    "examples/build_rs",
    "marine",
    "marine/tests/wasm_tests/arguments_passing",
    "marine/tests/wasm_tests/arrays_passing",
    "marine/tests/wasm_tests/records_passing",
    "marine/tests/wasm_tests/wasi",
    "marine-js",
    "tools/cli",
    "tools/repl",
]

[workspace.dependencies]
#wasmer-it = { git = "https://github.com/fluencelabs/interface-types", branch = "feat/add-store", package = "wasmer-interface-types-fl", version = "0.25.0" }
#it-memory-traits = {  git = "https://github.com/fluencelabs/interface-types", branch = "feat/add-store", package = "it-memory-traits", version = "0.3.1" }
#it-lilo = { git = "https://github.com/fluencelabs/interface-types", branch = "feat/add-store", package = "it-lilo", version = "0.4.1"}
#fluence-it-types = {  git = "https://github.com/fluencelabs/interface-types", branch = "feat/add-store", package = "fluence-it-types", version = "0.3.1", features = ["impls"] }

wasmer-it = { path = "../interface-types/wasmer-it", package = "wasmer-interface-types-fl", version = "0.25.0" }
it-memory-traits = {  path = "../interface-types/crates/it-memory-traits", package = "it-memory-traits", version = "0.3.1" }
it-lilo = { path = "../interface-types/crates/it-lilo", package = "it-lilo", version = "0.4.1"}
fluence-it-types = { path = "../interface-types/crates/it-types", package = "fluence-it-types", version = "0.3.1", features = ["impls"] }

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
