[workspace]
members = [
    "crates/it-generator",
    "crates/it-interfaces",
    "crates/it-parser",
    "crates/it-json-serde",
    "crates/min-it-version",
    "crates/module-info-parser",
    "crates/module-interface",
    "crates/utils",
    "examples/call_parameters",
    "examples/greeting",
    "examples/ipfs-node/effector",
    "examples/ipfs-node/pure",
    "examples/records/effector",
    "examples/records/pure",
    "examples/records/test-record",
    "examples/sqlite",
    "examples/url-downloader/curl_adapter",
    "examples/url-downloader/facade",
    "examples/url-downloader/local_storage",
    "examples/multiservice_marine_test",
    "examples/multiservice_marine_test/consumer",
    "examples/multiservice_marine_test/producer",
    "examples/build_rs",
    "fluence-app-service",
    "fluence-faas",
    "fluence-faas/tests/wasm_tests/arguments_passing",
    "fluence-faas/tests/wasm_tests/arrays_passing",
    "fluence-faas/tests/wasm_tests/records_passing",
    "runtime",
    "runtime/tests/wasm_tests/records_allocation",
    "web-runtime",
    "tools/cli",
    "tools/repl",
]

[patch.crates-io]
fluence-it-types = { git = " https://github.com/fluencelabs/interface-types", branch = "bug/memory-writer-not-updated", version = "0.3.1", features = ["impls"] }
it-to-bytes = { git = " https://github.com/fluencelabs/interface-types", branch = "bug/memory-writer-not-updated", version = "0.1.0" }
it-lilo = { git = " https://github.com/fluencelabs/interface-types", branch = "bug/memory-writer-not-updated", version = "0.4.0" }
it-memory-traits = { git = " https://github.com/fluencelabs/interface-types", branch = "bug/memory-writer-not-updated", version = "0.3.0" }
wasmer-interface-types-fl = { git = " https://github.com/fluencelabs/interface-types", branch = "bug/memory-writer-not-updated", version = "0.23.0" }


[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
