[workspace]
members = [
    "aquamarine-vm",
    "crates/module-info-parser",
    "crates/utils",
    "crates/wit-generator",
    "crates/wit-interfaces",
    "crates/wit-parser",
    "engine",
    "examples/call_parameters",
    "examples/greeting",
    "examples/ipfs-node/effector",
    "examples/ipfs-node/pure",
    "examples/records/effector",
    "examples/records/pure",
    "examples/records/test-record",
    "examples/sqlite",
    "examples/url-downloader/curl_adapter",
    "examples/url-downloader/facade",
    "examples/url-downloader/local_storage",
    "fluence-app-service",
    "fluence-faas",
    "fluence-faas/tests/wasm_tests/arguments_passing",
    "fluence-faas/tests/wasm_tests/arrays_passing",
    "fluence-faas/tests/wasm_tests/records_passing",
    "tools/cli",
    "tools/repl",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"

[patch.crates-io]
fluence-it-types = { git = "https://github.com/fluencelabs/interface-types", rev = "9095389a5af6e5e334be898437cee5b13f5b4909" }
wasmer-wit = { package = "wasmer-interface-types-fl", git = "https://github.com/fluencelabs/interface-types", rev = "9095389a5af6e5e334be898437cee5b13f5b4909" }
it-lilo-utils = { git = "https://github.com/fluencelabs/interface-types", rev = "9095389a5af6e5e334be898437cee5b13f5b4909" }
aqua-interpreter-interface = { git = "https://github.com/fluencelabs/air", branch = "bwu" }

#[patch."https://github.com/fluencelabs/interface-types"]
#it-lilo-utils = { rev = "9095389a5af6e5e334be898437cee5b13f5b4909" }
#wasmer-interface-types-fl = { git = "https://github.com/fluencelabs/interface-types", rev = "9095389a5af6e5e334be898437cee5b13f5b4909" }
