[workspace]
members = [
    "crates/fce_wit_interfaces",
    "crates/wit_parser",
    "examples/ipfs_node",
    "examples/ipfs_node/wasm/ipfs_node",
    "examples/ipfs_node/wasm/ipfs_rpc",
    "examples/simple_greeting",
    "fce",
    "tools/wit_embedder",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
