[package]
name = "FCE"
description = "Fluence compute engine, virtual machine based on Wasmer for the Fluence network"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
keywords = ["fluence", "webassembly", "wasmer", "execution environment"]
categories = ["webassembly"]
maintenance = { status = "actively-developed" }

[lib]
name = "fce"
path = "src/lib.rs"
#crate-type = ["cdylib"]

[[bin]]
name = "fce_cli"
path = "src/main.rs"

[dependencies]
wasmer-runtime = { git = "http://github.com/fluencelabs/wasmer", branch = "fluence" }
wasmer-runtime-core = { git = "http://github.com/fluencelabs/wasmer", branch = "fluence" }
wasmer-wasi = { git = "http://github.com/fluencelabs/wasmer", branch = "fluence" }
failure = "0.1.7"
lazy_static = "1.4.0"
sha2 = "0.8.1"
rustyline = "6.1.2"
exitfailure = "0.5.1"
boolinator = "2.4.0"
parity-wasm = "0.41.0"
pwasm-utils = "0.12.0"

[dev-dependencies]
reqwest = "0.10.4"
bytes = "0.5.4"
tokio = { version = "0.2.20", features = ["blocking", "macros"] }

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
