[workspace]
members = [
    "crates/fce_wit_interfaces",
    "examples/export_test",
    "examples/ipfs_node",
    "examples/ipfs_rpc",
    "fce",
    "tools/wit_embedder",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
