[workspace]
members = [
    "crates/wit-generator",
    "crates/wit-interfaces",
    "crates/wit-parser",
    "engine",
    "examples/greeting",
    "examples/ipfs-node/effector",
    "examples/ipfs-node/pure",
    "examples/records/effector",
    "examples/records/pure",
    "examples/records/test-record",
    "fluence-app-service",
    "fluence-faas",
    "fluence-faas/tests/json_wasm_tests/arguments_passing",
    "fluence-faas/tests/json_wasm_tests/inner_records",
    "tools/cli",
    "tools/repl",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
