[workspace]
members = [
    "crates/wit-generator",
    "crates/wit-interfaces",
    "crates/wit-parser",
    "engine",
    "examples/greeting",
    "examples/greeting/wasm/",
    "examples/ipfs_node",
    "examples/ipfs_node/wasm/ipfs_node",
    "examples/ipfs_node/wasm/ipfs_rpc",
    "examples/records",
    "examples/records/wasm/effector",
    "examples/records/wasm/pure",
    "examples/records/wasm/test-record",
    "fluence-faas",
    "fluence-service",
    "tools/cli",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
