[workspace]
members = [
    "aquamarine-vm",
    "crates/wit-generator",
    "crates/wit-interfaces",
    "crates/wit-parser",
    "engine",
    "examples/call_parameters",
    "examples/greeting",
    "examples/ipfs-node/effector",
    "examples/ipfs-node/pure",
    "examples/records/effector",
    "examples/records/pure",
    "examples/records/test-record",
    "examples/site-storage/site-storage",
    "examples/site-storage/curl",
    "examples/site-storage/local_storage",
    "examples/sqlite",
    "fluence-app-service",
    "fluence-faas",
    "fluence-faas/tests/wasm_tests/arguments_passing",
    "fluence-faas/tests/wasm_tests/arrays_passing",
    "fluence-faas/tests/wasm_tests/inner_records",
    "tools/cli",
    "tools/repl",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
