[workspace]
members = [
    "core",
    "core/tests/wasm_tests/lilo_after_2gb",
    "crates/fluence-app-service",
    "crates/it-generator",
    "crates/it-interfaces",
    "crates/it-parser",
    "crates/it-json-serde",
    "crates/min-it-version",
    "crates/module-info-parser",
    "crates/module-interface",
    "crates/utils",
    "examples/call_parameters",
    "examples/greeting",
    "examples/greeting_record",
    "examples/ipfs-node/effector",
    "examples/ipfs-node/pure",
    "examples/motivational-example/donkey",
    "examples/motivational-example/shrek",
    "examples/records/effector",
    "examples/records/pure",
    "examples/records/test-record",
    "examples/sqlite",
    "examples/url-downloader/curl_adapter",
    "examples/url-downloader/facade",
    "examples/url-downloader/local_storage",
    "examples/multiservice_marine_test",
    "examples/multiservice_marine_test/consumer",
    "examples/multiservice_marine_test/producer",
    "examples/build_rs",
    "marine",
    "marine/tests/wasm_tests/arguments_passing",
    "marine/tests/wasm_tests/arrays_passing",
    "marine/tests/wasm_tests/records_passing",
    "marine-js",
    "tools/cli",
    "tools/repl",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"

[patch.crates-io]
polyplets = { version = "0.3.0", git = "https://github.com/fluencelabs/aquavm", branch = "bug/wasm_memory_leak"}
marine-rs-sdk = {version = "0.7.0", git = "https://github.com/fluencelabs/marine-rs-sdk", branch = "feat/VM-115-wasm_ctors_workaround"}
marine-rs-sdk-main = {version = "0.7.0", git = "https://github.com/fluencelabs/marine-rs-sdk", branch = "feat/VM-115-wasm_ctors_workaround"}
marine-macro = {version = "0.7.0", git = "https://github.com/fluencelabs/marine-rs-sdk", branch = "feat/VM-115-wasm_ctors_workaround"}
marine-macro-impl = {version = "0.7.0", git = "https://github.com/fluencelabs/marine-rs-sdk", branch = "feat/VM-115-wasm_ctors_workaround"}
marine-sqlite-connector = {version = "0.5.2", git = "https://github.com/fluencelabs/sqlite-wasm-connector", branch = "update-sdk"}