[toolchain]
channel = "nightly-2023-03-12"
components = [
  "clippy",
  "fmt",
]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "wasm32-wasi",
  "wasm32-unknown-unknown",
]
