[package]
name = "fce"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
fce_wit_interfaces = { path = "../crates/fce_wit_interfaces", version = "0.1.0" }
wit_parser = { path = "../crates/wit_parser", version = "0.1.0" }

wasmer-runtime = { git = "https://github.com/fluencelabs/wasmer", branch = "fluence" }
# dynamicfunc-fat-closures allows using state inside DynamicFunc
wasmer-core = { package = "wasmer-runtime-core", git = "http://github.com/fluencelabs/wasmer", branch = "fluence", features = ["dynamicfunc-fat-closures"] }
wasmer-wit = { package = "wasmer-interface-types", git = "http://github.com/fluencelabs/interface-types", branch = "master", features = ["serde"] }
wasmer-wasi = { git = "https://github.com/fluencelabs/wasmer", branch = "fluence" }
serde = { version = "1.0.114", default-features = false, features = [ "derive" ] }

multimap = "0.8.1"
parity-wasm = "0.41.0"
pwasm-utils = "0.12.0"
log = "0.4.8"

