[package]
name = "fce-wit-parser"
description = "Fluence FCE interface type helper crate"
version = "0.1.5"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fce_wit_parser"
path = "src/lib.rs"

[dependencies]
fce-wit-interfaces = { path = "../wit-interfaces", version = "0.1.3" }

anyhow = "1.0.31"
walrus = "0.17.0"
wasmer-core = { package = "wasmer-runtime-core-fl", version = "0.17.0"}
wasmer-wit = { package = "wasmer-interface-types-fl", path = "/Users/mike/dev/work/fluence/wasm/interface-types", version = "=0.17.6" }
#wasmer-wit = { package = "wasmer-interface-types-fl", version = "=0.17.6" }
