[package]
name = "wit-parser"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
name = "wit_parser"
path = "src/lib.rs"

[dependencies]
walrus = "0.17.0"
wasmer-core = { package = "wasmer-runtime-core", git = "https://github.com/fluencelabs/wasmer", branch = "fluence" }
wasmer-wit = { package = "wasmer-interface-types", git = "https://github.com/fluencelabs/interface-types", branch = "struct_support" }
fce-wit-interfaces = { path = "../fce-wit-interfaces" }

anyhow = "1.0.31"
