[package]
name = "fce-wit-parser"
description = "Fluence FCE interface type parser"
version = "0.5.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fce_wit_parser"
path = "src/lib.rs"

[dependencies]
fce-wit-interfaces = { path = "../wit-interfaces", version = "0.3.0" }

anyhow = "1.0.31"
walrus = "0.18.0"
wasmer-core = { package = "wasmer-runtime-core-fl", version = "0.17.0"}
wasmer-wit = { package = "wasmer-interface-types-fl", version = "0.20.0" }
nom = "5.1"

semver = "0.11.0"
serde = "=1.0.118"
thiserror = "1.0.24"
