[package]
name = "it-json-serde"
description = "Fluence Marine interface-types serde tools"
version = "0.3.3"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "it_json_serde"
path = "src/lib.rs"

[dependencies]
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.24.1"}

serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_derive = "1.0.144"
thiserror = "1.0.34"
