[package]
name = "wasm-greeting"
version = "0.1.0"
authors = ["Fluence Labs"]
description = "The greeting module for the Fluence network"
repository = "https://github.com/fluencelabs/marine/tree/master/examples/greeting"
edition = "2018"
publish = false

[[bin]]
name = "greeting"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.6.11"

[dev-dependencies]
marine-rs-sdk-test = {path="../../../marine-rs-sdk/sdk-test"}

[build-dependencies]
marine-test-macro-impl = {path="../../../marine-rs-sdk/crates/marine-test-macro-impl"}
quote = "1.0.9"
proc-macro2 = "1.0.26"
marine-rs-sdk-test = {path="../../../marine-rs-sdk/sdk-test"}
