[package]
name = "wasm-greeting"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "greeting"
path = "src/main.rs"

[dependencies]
#fluence = { git = "https://github.com/fluencelabs/rust-sdk", branch = "support_references" }
fluence = { path = "/Users/mike/dev/work/fluence/wasm/rust-sdk/fluence" }
