[[core_module]]
    name = "ipfs_node.wasm"
    mem_pages_count = 100
    logger_enabled = true

    [core_module.imports]
    mysql = "/usr/bin/mysql"
    ipfs = "/usr/local/bin/ipfs"

    [core_module.wasi]
    envs = ["IPFS_ADDR=/dns4/relay02.fluence.dev/tcp/15001"]
    preopened_files = ["./wasm/artifacts"]
    mapped_dirs = { "tmp" = "./wasm/artifacts" }

[rpc_module]
    mem_pages_count = 100
    logger_enabled = true

    [rpc_module.wasi]
    envs = []
    preopened_files = ["./wasm/artifacts"]
    mapped_dirs = { "tmp" = "./wasm/artifacts" }
