modules_dir = "wasm/artifacts/wasm_modules"
service_base_dir = "/Users/tmp"

[[module]]
    name = "ipfs_node.wasm"
    mem_pages_count = 100
    logger_enabled = true

    [module.imports]
    ipfs = "/usr/local/bin/ipfs"

    [module.wasi]
    envs = ["IPFS_ADDR=/dns4/relay02.fluence.dev/tcp/15001", "timeout=1s"]

[[module]]
    name = "ipfs_rpc.wasm"
    mem_pages_count = 100
    logger_enabled = true
