[package]
name = "marine-wasmtime-backend"
description = "Fluence Marine Wasm backend interface implementation for Wasmtime"
version = "0.2.2"
edition = "2021"
authors = ["Fluence Labs"]
license = "Apache-2.0"

[dependencies]
marine-wasm-backend-traits = {path = "../wasm-backend-traits", version = "0.2.1"}
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.26.1" }
it-memory-traits = "0.4.0"

# all default features except async
wasmtime = {version = "9.0.4" }
wasmtime-wasi = "9.0.4"
multimap = "0.8.3"
paste = "1.0.13"
anyhow = "1.0.71"
log = "0.4.19"
futures = "0.3.28"
async-trait = "0.1.71"