[package]
name = "marine-wasmtime-backend"
version = "0.2.0"
edition = "2021"
authors = ["Fluence Labs"]
license = "Apache-2.0"

[dependencies]
marine-wasm-backend-traits = {path = "../wasm-backend-traits", version = "0.2.0"}
wasmer-it = { workspace = true }
it-memory-traits = { workspace = true }

# all default features except async
wasmtime = {version = "6.0.1", default-features = false, features = ["cache", "wat", "jitdump", "parallel-compilation", "cranelift", "pooling-allocator", "vtune"]}
wasmtime-wasi = "6.0.1"
multimap = "0.8.3"
paste = "1.0.9"
anyhow = "1.0.68"
log = "0.4.1"
