[package]
name = "fce-wit-generator"
description = "Fluence FCE interface type helper crate"
version = "0.1.2"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fce_wit_generator"
path = "src/lib.rs"

[dependencies]
fce-wit-parser = { path = "../wit-parser", version = "0.1.1"}
walrus = "0.17.0"
fluence-sdk-wit = {git = "https://github.com/fluencelabs/rust-sdk", version = "0.2.0", branch = "record_support" }
once_cell = "1.4.0"
wasmer-wit = { package = "wasmer-interface-types-fl", git = "https://github.com/fluencelabs/interface-types/", branch = "record_refactoring"}
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.56"
