[package]
name = "fce-wit-generator"
description = "Fluence FCE interface type helper crate"
version = "0.1.4"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fce_wit_generator"
path = "src/lib.rs"

[dependencies]
fce-wit-parser = { path = "../wit-parser", version = "0.1.3"}
fluence-sdk-wit = { git = "https://github.com/fluencelabs/rust-sdk", branch = "record_support" }

walrus = "0.17.0"
wasmer-wit = { package = "wasmer-interface-types-fl", version = "=0.17.4" }
once_cell = "1.4.0"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.56"
