[package]
name = "wit-generator"
description = "Fluence Wasm interface type generator"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
wit-parser = { path = "../wit-parser" }
walrus = "0.17.0"
fluence-sdk-wit = "0.2.0"
once_cell = "1.4.0"
wasmer-wit = { package = "wasmer-interface-types-fl", version = "0.17.0", features = ["serde"] }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.56"
