[package]
name = "marine-wit-interfaces"
description = "Fluence Marine interface types helper crate"
version = "0.3.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_wit_interfaces"
path = "src/lib.rs"

[dependencies]
wasmer-wit = { package = "wasmer-interface-types-fl", version = "0.20.0" }
multimap = "0.8.1"
