[package]
name = "fce-wit-interfaces"
description = "Fluence FCE interface type helper crate"
version = "0.1.6"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fce_wit_interfaces"
path = "src/lib.rs"

[dependencies]
wasmer-wit = { package = "wasmer-interface-types-fl", version = "=0.17.11" }
multimap = "0.8.1"
