[package]
name = "fce-wit-interfaces"
description = "Fluence FCE interface type helper crate"
version = "0.2.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fce_wit_interfaces"
path = "src/lib.rs"

[dependencies]
wasmer-wit = { package = "wasmer-interface-types-fl", git = "https://github.com/fluencelabs/interface-types", branch = "optimizations" }
multimap = "0.8.1"
