version: 2.1
jobs:
  fce:
    docker:
      - image: circleci/rust:latest
    environment:
      RUST_BACKTRACE: 1
      #RUST_TEST_THREADS: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - fce04-{{ checksum "Cargo.lock" }}
      - run: |
          rustup toolchain install nightly-2020-04-20
          rustup default nightly-2020-04-20
          rustup override set nightly-2020-04-20

          rustup component add rustfmt
          rustup component add clippy --toolchain nightly
          rustup target add wasm32-wasi

          cargo install fcli

          cargo fmt --all -- --check --color always
          cargo check -v --all-features

          (cd ./examples; ./build.sh)

          cargo test --release -v --all-features
          cargo clippy -v

      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: fce04-{{ checksum "Cargo.lock" }}

workflows:
  version: 2.1
  fce:
    jobs:
      - fce
