[package]
name = "wit_parser"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
name = "wit_parser"
path = "src/lib.rs"

[dependencies]
walrus = "0.17.0"
wasmer-core = { package = "wasmer-runtime-core", version = "0.17.0"}
wasmer-wit = { package = "wasmer-interface-types", git = "https://github.com/fluencelabs/interface-types", branch = "master" }
fce_wit_interfaces = { path = "../fce_wit_interfaces" }

anyhow = "1.0.31"
