networks:
  fluence:
    driver: bridge
    ipam:
      config:
      - subnet: 10.50.10.0/24

services:
  fluence-1:
    image: docker.fluence.dev/marine:${GITHUB_HEAD_REF}
    ports:
      - 7771:7771
      - 9991:9991
    command:
      - -t=7771
      - -w=9991
      - --bootstraps=/dns/fluence-1/tcp/7771
      # 12D3KooWBM3SdXWqGaawQDGQ6JprtwswEg3FWGvGhmgmMez1vRbR
      - -k=hK62afickoeP2uZbmSkAYXxxqP8ozq16VRN7qfTP719EHC5V5tjrtW57BSjUr8GvsEXmJRbtejUWyPZ2rZMyQdq
    networks:
      fluence:
        ipv4_address: 10.50.10.10

  fluence-2:
    image: docker.fluence.dev/marine:${GITHUB_HEAD_REF}
    ports:
      - 7772:7772
      - 9992:9992
    command:
      - -t=7772
      - -w=9992
      - --bootstraps=/dns/fluence-1/tcp/7771
      # 12D3KooWMTX8WyWBykinniE7sZnQjT8AXv6XX8rNYreB3GCSSE5f
      - -k=FYNUpSG9773RadACVyQJwhkUVznLNpM7qh2RqVbqa6Mn62TkEQSF9FUM6qa5nK3f8aksb4C1WaCRpF7j1EEHvK3
    networks:
      fluence:
        ipv4_address: 10.50.10.20

  fluence-3:
    image: docker.fluence.dev/marine:${GITHUB_HEAD_REF}
    ports:
      - 7773:7773
      - 9993:9993
    command:
      - -t=7773
      - -w=9993
      - --bootstraps=/dns/fluence-1/tcp/7771
      # 12D3KooWRT8V5awYdEZm6aAV9HWweCEbhWd7df4wehqHZXAB7yMZ
      - -k=2n2wBVanBeu2GWtvKBdrYK9DJAocgG3PrTUXMharq6TTfxqTL4sLdXL9BF23n6rsnkAY5pR9vBtx2uWYDQAiZdrX
    networks:
      fluence:
        ipv4_address: 10.50.10.30

  fluence-4:
    image: docker.fluence.dev/marine:${GITHUB_HEAD_REF}
    ports:
      - 7774:7774
      - 9994:9994
    command:
      - -t=7774
      - -w=9994
      - --bootstraps=/dns/fluence-1/tcp/7771
      # 12D3KooWBzLSu9RL7wLP6oUowzCbkCj2AGBSXkHSJKuq4wwTfwof
      - -k=4zp8ucAikkjB8CmkufYiFBW4QCDUCbQG7yMjviX7W8bMyN5rfChQ2Pi5QCWThrCTbAm9uq5nbFbxtFcNZq3De4dX
    networks:
      fluence:
        ipv4_address: 10.50.10.40

  fluence-5:
    image: docker.fluence.dev/marine:${GITHUB_HEAD_REF}
    ports:
      - 7775:7775
      - 9995:9995
    command:
      - -t=7775
      - -w=9995
      - --bootstraps=/dns/fluence-1/tcp/7771
      # 12D3KooWBf6hFgrnXwHkBnwPGMysP3b1NJe5HGtAWPYfwmQ2MBiU
      - -k=3ry26rm5gkJXvdqRH4FoM3ezWq4xVVsBQF7wtKq4E4pbuaa6p1F84tNqifUS7DdfJL9hs2gcdW64Wc342vHZHMUp
    networks:
      fluence:
        ipv4_address: 10.50.10.50

  fluence-6:
    image: docker.fluence.dev/marine:${GITHUB_HEAD_REF}
    ports:
      - 7776:7776
      - 9996:9996
    command:
      - -t=7776
      - -w=9996
      - --bootstraps=/dns/fluence-1/tcp/7771
      # 12D3KooWPisGn7JhooWhggndz25WM7vQ2JmA121EV8jUDQ5xMovJ
      - -k=5Qh8bB1sF28uLPwr3HTvEksCeC6mAWQvebCfcgv9y6j4qKwSzNKm2tzLUg4nACUEo2KZpBw11gNCnwaAdM7o1pEn
    networks:
      fluence:
        ipv4_address: 10.50.10.60
