[package]
name = "test-record"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
name = "test_record"
path = "src/test_record.rs"

[dependencies]
fluence = { git = "https://github.com/fluencelabs/rust-sdk", branch = "logger-i32" }
