[package]
name = "fluence-app-service"
description = "Fluence Application Service"
version = "0.23.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
marine-runtime = { path = "../../marine", version = "0.24.0" }
marine-min-it-version = { path = "../../crates/min-it-version", version = "0.2.1" }
marine-wasm-backend-traits = {path = "../wasm-backend-traits", version = "0.1.0"}

maplit = "1.0.2"
log = "0.4.17"
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.89"
toml = "0.5.9"
#wasmer-wasi = { workspace = true }

[dev-dependencies]
marine-wasmer-backend = { path = "../wasmer-backend", version = "0.1.0"}

[features]
default = ["wasmtime"]
raw-module-api = ["marine-runtime/raw-module-api"]
wasmtime = ["marine-runtime/wasmtime"]
wasmer = ["marine-runtime/wasmer"]
