[package]
name = "call_parameters"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
name = "call_parameters"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.10.3", features = ["logger"], git = "https://github.com/fluencelabs/marine-rs-sdk", branch = "feat/worker-id-in-call-params" }
