[package]
name = "marine-core"
description = "Core of Marine, the Fluence Wasm Runtime"
version = "0.18.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_core"
path = "src/lib.rs"

[dependencies]
marine-module-info-parser = { path = "../crates/module-info-parser", version = "0.5.0" }
marine-it-interfaces = { path = "../crates/it-interfaces", version = "0.7.3" }
marine-it-parser = { path = "../crates/it-parser", version = "0.11.0" }
marine-it-generator = { path = "../crates/it-generator", version = "0.9.4" }
marine-module-interface = { path = "../crates/module-interface", version = "0.6.0" }
marine-utils = { path = "../crates/utils", version = "0.4.0" }
marine-min-it-version = { path = "../crates/min-it-version", version = "0.2.0" }

wasmer-runtime = { package = "wasmer-runtime-fl", version = "=0.17.1" }
# dynamicfunc-fat-closures allows using state inside DynamicFunc
wasmer-core = { package = "wasmer-runtime-core-fl", version = "=0.17.1", features = ["dynamicfunc-fat-closures"] }
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.24.1"}
wasmer-wasi = { package = "wasmer-wasi-fl", version = "0.17.1" }
it-lilo = "0.4.1"
it-memory-traits = "0.3.1"
bytesize = "1.1.0"

multimap = "0.8.3"
boolinator = "2.4.0"
parity-wasm = "0.45.0"
pwasm-utils = "0.19.0"
once_cell = "1.16.0"
semver = "1.0.14"
serde = "1.0.147"
log = "0.4.17"

paste = "1.0.9"

anyhow = "1.0.66"
thiserror = "1.0.37"

[dev-dependencies]
reqwest = "0.11.13"
bytes = "1.3.0"
tokio = { version = "1.22.0", features = ["rt", "macros"] }
once_cell = "1.16.0"
