[package]
name = "marine-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluence-app-service = { path = "../../crates/fluence-app-service", version = "0.28.0" }

clap = { version = "4.2.7", features = ["derive", "env"] }
serde = "1.0.183"
serde_json = "1.0.104"
tracing-subscriber = "0.3.17"
