[package]
name = "marine-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluence-app-service = { path = "../../crates/fluence-app-service", version = "0.28.0" }
marine-rs-sdk = "0.8.1"

anyhow = "1.0.72"
clap = { version = "4.2.7", features = ["derive", "env"] }
env_logger = "0.10.0"
log = "0.4.19"
serde = "1.0.183"
serde_derive = "1.0.183"
serde_json = "1.0.104"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [ "env-filter", "json", "smallvec", "time", "fmt" ] }
