[package]
name = "facade"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[[bin]]
name = "facade"
path = "src/main.rs"

[dependencies]
fluence = { version = "=0.2.12", features = ["logger"]}
anyhow = "1.0.31"
log = "0.4.8"
