[package]
name = "facade"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "facade"
path = "src/main.rs"

[dependencies]
#fluence = { git = "https://github.com/fluencelabs/rust-sdk", features = ["logger"] }
fluence = { path = "/Users/mike/dev/work/fluence/wasm/rust-sdk/fluence", features = ["logger"] }
anyhow = "1.0.31"
log = "0.4.8"
