[package]
name = "marine-utils"
description = "Fluence Marine utils crate"
version = "0.23.1-something-7.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_utils"
path = "src/lib.rs"
