[package]
name = "donkey"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = { workspace = true }
publish = false

[[bin]]
name = "donkey"
path = "src/main.rs"

[dependencies]
marine-rs-sdk ={ version = "0.7.0", features = ["logger"] }
