[package]
name = "donkey"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
name = "donkey"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { workspace = true }
