[package]
name = "wasm-sqlite-test"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "sqlite_test"
path = "src/main.rs"

[dependencies]
fluence = "0.6.1"
fce-sqlite-connector = { git = "https://github.com/fluencelabs/sqlite-wasm-connector", branch = "fluence_0_6_0" }
