[package]
name = "wasm-sqlite-test"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
name = "sqlite_test"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { workspace = true }
marine-sqlite-connector = "0.9.0"
