modules_dir = "artifacts/"
total_memory_limit = "10 MiB"

[[module]]
    name = "sqlite3"
    logger_enabled = false

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "/tmp" }

[[module]]
    name = "sqlite_test"
    logger_enabled = false

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "/tmp" }
