modules_dir = "artifacts/"

[[module]]
    name = "sqlite3"
    mem_pages_count = 100
    logger_enabled = false

    [module.wasi]
    preopened_files = ["/Users/mike/dev/work/fluence/wasm/fce/examples/sqlite"]
    mapped_dirs = { "var" = "/Users/mike/dev/work/fluence/wasm/fce/examples/sqlite" }

[[module]]
    name = "sqlite_test"
    mem_pages_count = 1
    logger_enabled = false

    [module.wasi]
    preopened_files = ["/Users/mike/dev/work/fluence/wasm/fce/examples/sqlite"]
    mapped_dirs = { "var" = "/Users/mike/dev/work/fluence/wasm/fce/examples/sqlite" }
