[package]
name = "wasm_greeting"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
name = "greeting"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
fluence = { git = "https://github.com/fluencelabs/rust-sdk" }
