[package]
name = "marine-it-interfaces"
description = "Fluence Marine interface types helper crate"
version = "0.7.2"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_it_interfaces"
path = "src/lib.rs"

[dependencies]
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.23.1" }
multimap = "0.8.3"
