[package]
name = "marine-it-parser"
description = "Fluence Marine interface types parser"
version = "0.6.1"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_it_parser"
path = "src/lib.rs"

[dependencies]
marine-it-interfaces = { path = "../it-interfaces", version = "0.4.0" }

anyhow = "1.0.31"
walrus = "0.18.0"
wasmer-core = { package = "wasmer-runtime-core-fl", version = "0.17.0"}
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.20.0" }
nom = "5.1"

semver = "0.11.0"
serde = "=1.0.118"
thiserror = "1.0.24"
