[package]
name = "marine-module-info-parser"
description = "Fluence Marine Wasm module info (manifest and version) parser"
version = "0.1.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_module_info_parser"
path = "src/lib.rs"

[dependencies]
fluence-sdk-main = "0.6.3"

wasmer-core = { package = "wasmer-runtime-core-fl", path = "/Users/mike/dev/work/fluence/wasm/wasmer/lib/runtime-core", version = "0.17.0" }

anyhow = "1.0.31"
chrono = "0.4.19"
walrus = "0.18.0"
semver = "0.11.0"

serde = "=1.0.118"
thiserror = "1.0.24"
