[package]
name = "marine-module-info-parser"
description = "Fluence Marine Wasm module info (manifest and version) parser"
version = "0.5.1"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_module_info_parser"
path = "src/lib.rs"

[dependencies]
marine-rs-sdk-main = "0.7.1"

wasmer-core = { package = "wasmer-runtime-core-fl", version = "=0.17.1" }

anyhow = "1.0.66"
chrono = "0.4.23"
walrus = "0.19.0"
semver = "1.0.14"

serde = "1.0.147"
thiserror = "1.0.37"
