[package]
name = "fce-module-info-parser"
description = "Fluence FCE Wasm module info (manifest and version) parser"
version = "0.1.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fce_module_info_parser"
path = "src/lib.rs"

[dependencies]
fluence-sdk-main = { git = "https://github.com/fluencelabs/rust-sdk" }

wasmer-core = { package = "wasmer-runtime-core-fl", version = "0.17.0" }

anyhow = "1.0.31"
walrus = "0.18.0"
semver = "0.11.0"

serde = "=1.0.118"
thiserror = "1.0.24"
