[package]
name = "marine-module-info-parser"
description = "Fluence Marine Wasm module info (manifest and version) parser"
version = "0.5.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2021"

[lib]
name = "marine_module_info_parser"
path = "src/lib.rs"

[dependencies]
marine-rs-sdk-main = "0.7.1"

wasmer = { version = "3.1.0", default-features = false, features = ["sys-default"] }
marine-wasm-backend-traits = { path = "../wasm-backend-traits", version = "0.1.0"}

anyhow = "1.0.64"
chrono = "0.4.22"
walrus = "0.19.0"
semver = "1.0.13"

serde = "1.0.144"
thiserror = "1.0.34"
