[package]
name = "curl_adapter"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
path = "src/main.rs"
name = "curl_adapter"

[dependencies]
#fluence = { git = "https://github.com/fluencelabs/rust-sdk", features = ["logger"] }
fluence = { path = "/Users/mike/dev/work/fluence/wasm/rust-sdk/fluence", features = ["logger"] }
log = "0.4.8"
