[package]
name = "curl_adapter"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "curl_adapter"

[dependencies]
fluence = { version = "=0.2.12", features = ["logger"]}
log = "0.4.8"
