[package]
name = "curl_adapter"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
path = "src/main.rs"
name = "curl_adapter"

[dependencies]
#fluence = { version = "=0.2.18", features = ["logger"]}
fluence = { git = "https://github.com/fluencelabs/rust-sdk", branch = "mounted_binary_result", features = ["logger"] }
log = "0.4.8"
