[package]
name = "curl_adapter"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
path = "src/main.rs"
name = "curl_adapter"

[dependencies]
marine-rs-sdk = { workspace = true }
log = "0.4.8"
