[package]
name = "wasm-failing"
version = "0.1.0"
authors = ["Fluence Labs"]
description = "The failing module for the Fluence network"
repository = "https://github.com/fluencelabs/marine/tree/master/examples/failing"
edition = "2021"
publish = false

[[bin]]
name = "failing"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.8.1"

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
