[package]
name = "marine-min-it-version"
version = "0.1.1"
description = "Fluence Marine interface types minimum supported version checker"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_min_it_version"
path = "src/lib.rs"

[dependencies]
once_cell = "1.13.1"
semver = "0.11.0"
