[package]
name = "record-pure"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = { workspace = true }
publish = false

[[bin]]
name = "records_pure"
path = "src/main.rs"

[dependencies]
marine-rs-sdk ="0.7.0"
test-record = { path = "../test-record" }
