[package]
name = "js-backend"
version = "0.1.0"
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marine-wasm-backend-traits = {version = "0.1.0", path = "../wasm-backend-traits"}
wasmer-it = { workspace = true }