[package]
name = "js-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marine-wasm-backend-traits = {version = "0.1.0", path = "../wasm-backend-traits"}
it-memory-traits = "0.3.1"