[package]
name = "mrepl"
description = "Fluence Marine REPL intended for testing purposes"
version = "0.18.7"
authors = ["Fluence Labs"]
repository = "https://github.com/fluencelabs/marine/tools/repl"
license = "Apache-2.0"
edition = "2018"

[[bin]]
name = "mrepl"
path = "src/main.rs"

[dependencies]
fluence-app-service = { path = "../../crates/fluence-app-service", version = "0.22.3", features = ["raw-module-api"] }
marine-rs-sdk-main = { version = "0.7.1", features = ["logger"] }

anyhow = "1.0.66"
clap = "2.34.0"
serde = "1.0.147"
serde_json = "1.0.89"
wasmer-wasi = { package = "wasmer-wasi-fl", version = "0.17.1"}

env_logger = "0.9.3"
check-latest = "1.0.1"
log = "0.4.17"
rustyline = { version = "10.0.0", features = ["with-fuzzy"] }
rustyline-derive = "0.7.0"
rustop = "1.1.2"
itertools = "0.10.5"
uuid = { version = "1.2.2", features = ["v4"] }
termion = "1.5.6"
