[package]
name = "mrepl"
description = "Fluence Marine REPL intended for testing purposes"
version = "0.24.0"
authors = ["Fluence Labs"]
repository = "https://github.com/fluencelabs/marine/tools/repl"
license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "mrepl"
path = "src/main.rs"

[dependencies]
fluence-app-service = { path = "../../crates/fluence-app-service", version = "0.29.0", features = ["raw-module-api"] }
marine-rs-sdk-main = { version = "0.10.0", default-features = false, features = ["logger"] }
marine-wasm-backend-traits = {path = "../../crates/wasm-backend-traits", version = "0.3.0"}

anyhow = "1.0.75"
clap = "2.34.0"
serde = "1.0.147"
serde_json = "1.0.107"

env_logger = "0.10.0"
check-latest = { version = "1.0.2", optional = true }
log = "0.4.20"
rustyline = { version = "10.0.0", features = ["with-fuzzy"] }
rustyline-derive = "0.7.0"
rustop = "1.1.2"
itertools = "0.10.5"
uuid = { version = "1.4.0", features = ["v4"] }
termion = "1.5.6"

[features]
check-latest = ["dep:check-latest"]
