[package]
name = "frepl"
description = "Fluence FCE REPL intended for testing purposes"
version = "0.7.0"
authors = ["Fluence Labs"]
repository = "https://github.com/fluencelabs/fce/tools/repl"
license = "Apache-2.0"
edition = "2018"

[[bin]]
name = "fce-repl"
path = "src/main.rs"

[dependencies]
fluence-app-service = { path = "../../fluence-app-service", version = "0.7.0", features = ["raw-module-api"] }
fluence-sdk-main = { version = "0.6.1", features = ["logger"] }

anyhow = "1.0.31"
clap = "2.33.1"
serde_json = "1.0.57"
wasmer-wasi = { package = "wasmer-wasi-fl", version = "0.17.1"}

env_logger = "0.7.1"
check-latest = "1.0.0"
log = "0.4.14"
rustyline = { version = "6.1.2", features = ["with-fuzzy"] }
rustyline-derive = "0.3.1"
rustop = "1.1.1"
itertools = "0.9.0"
uuid = { version = "0.8.1", features = ["v4"] }
termion = "1.5.6"
