[package]
name = "marine"
description = "Fluence Marine command line tool"
version = "0.6.2"
authors = ["Fluence Labs"]
repository = "https://github.com/fluencelabs/marine/tools/cli"
license = "Apache-2.0"
edition = "2018"

[[bin]]
name = "marine"
path = "src/main.rs"

[dependencies]
marine-it-generator = { path = "../../crates/it-generator", version = "0.5.1" }
marine-it-parser = { path = "../../crates/it-parser", version = "0.6.0" }
marine-module-info-parser = { path = "../../crates/module-info-parser", version = "0.1.0" }

semver = "0.11.0"
walrus = "0.18.0"

thiserror = "1.0.24"
anyhow = "1.0.31"
check-latest = "1.0.0"
clap = "2.33.1"
exitfailure = "0.5.1"
serde = "=1.0.118"
serde_json = "1.0.56"
termion = "1.5.6"
