[package]
name = "fce_cli"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[[bin]]
name = "fce"
path = "src/main.rs"

[dependencies]
wit-generator = { path = "../../crates/wit-generator" }
wit-parser = { path = "../../crates/wit-parser" }

clap = "2.33.1"
exitfailure = "0.5.1"
failure = "0.1.5"
serde = "1.0.114"
serde_json = "1.0.56"
