[package]
name = "marine"
description = "Fluence Marine command line tool"
version = "0.12.4"
authors = ["Fluence Labs"]
repository = "https://github.com/fluencelabs/marine/tools/cli"
license = "Apache-2.0"
edition = "2018"

[[bin]]
name = "marine"
path = "src/main.rs"

[dependencies]
marine-it-generator = { path = "../../crates/it-generator", version = "0.9.4" }
marine-it-parser = { path = "../../crates/it-parser", version = "0.11.0" }
marine-module-info-parser = { path = "../../crates/module-info-parser", version = "0.5.0" }

cargo_toml = "0.13.0"
semver = "1.0.14"
walrus = "0.19.0"
Inflector = "0.11.4"
toml = "0.5.9"
atty = "0.2.14"
thiserror = "1.0.37"
anyhow = "1.0.66"
check-latest = "1.0.1"
clap = "2.34.0"
exitfailure = "0.5.1"
serde = "1.0.147"
serde_json = "1.0.89"
termion = "1.5.6"
