[package]
name = "fcli"
description = "Fluence FCE command line tool"
version = "0.2.0"
authors = ["Fluence Labs"]
repository = "https://github.com/fluencelabs/fce/tools/cli"
license = "Apache-2.0"
edition = "2018"

[[bin]]
name = "fce"
path = "src/main.rs"

[dependencies]
fce-wit-generator = { path = "../../crates/wit-generator", version = "0.1.30" }
fce-wit-parser = { path = "../../crates/wit-parser", version = "0.2.0" }

anyhow = "1.0.31"
clap = "2.33.1"
exitfailure = "0.5.1"
serde = "=1.0.118"
serde_json = "1.0.56"
