[package]
name = "ipfs-effector"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = false

[[bin]]
name = "ipfs_effector"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { workspace = true }
log = "0.4.14"
