[package]
name = "wit_embedder"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
wit_parser = { path = "../../crates/wit_parser" }
clap = "2.33.1"
exitfailure = "0.5.1"
failure = "0.1.5"
