[package]
name = "wit_embedder"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
fce_wit_interfaces = { path = "../../crates/fce_wit_interfaces" }
clap = "2.33.1"
exitfailure = "0.5.1"
failure = "0.1.5"
