modules_dir = "artifacts/wasm_modules"

[[module]]
    name = "ipfs_node.wasm"
    mem_pages_count = 100
    logger_enabled = true

    [module.imports]
    ipfs = "/usr/local/bin/ipfs"

    [module.wasi]
    envs = ["IPFS_ADDR=/dns4/relay02.fluence.dev/tcp/15001", "timeout=1s"]

[[module]]
    name = "ipfs_pure.wasm"
    mem_pages_count = 100
    logger_enabled = true
