[package]
name = "marine-module-interface"
description = "Fluence Marine module interface"
version = "0.6.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_module_interface"
path = "src/lib.rs"

[dependencies]
marine-it-interfaces = { path = "../it-interfaces", version = "0.7.3" }

anyhow = "1.0.64"
walrus = "0.19.0"
wasmer-it = { workspace = true }
nom = "5.1"

itertools = "0.10.3"
semver = "1.0.13"
serde = "1.0.144"
thiserror = "1.0.34"
