[package]
name = "marine-module-interface"
description = "Fluence Marine module interface"
version = "0.1.0"
authors = ["Fluence Labs"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "marine_module_interface"
path = "src/lib.rs"

[dependencies]
marine-it-interfaces = { path = "../it-interfaces", version = "0.4.0" }
#marine-it-generator = { path = "../it-generator", verision = "0.5.2"}

anyhow = "1.0.31"
walrus = "0.18.0"
wasmer-core = { package = "wasmer-runtime-core-fl", version = "0.17.0"}
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.20.0" }
nom = "5.1"

itertools = "0.10.0"
semver = "0.11.0"
serde = "=1.0.118"
thiserror = "1.0.24"
