[package]
name = "marine-js"
version = "0.3.3"
edition = "2018"
description = "Web version of the marine runtime"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
marine-it-interfaces = { path = "../crates/it-interfaces", version = "0.7.3" }
marine-module-interface = { path = "../crates/module-interface", version = "0.6.0" }
marine-utils = { path = "../crates/utils", version = "0.4.0" }
marine-min-it-version = { path = "../crates/min-it-version", version = "0.2.0" }
it-json-serde = { path = "../crates/it-json-serde", version = "0.3.4" }

marine-rs-sdk = "0.7.1"
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.24.1"}
fluence-it-types = {version = "0.3.1", features = ["impls"] }
it-lilo = "0.4.0"
it-memory-traits = "0.3.0"

wasm-bindgen = "0.2"
nom = "5.1"
itertools = "0.10.3"
multimap = "0.8.3"
boolinator = "2.4.0"
bytesize = {version = "1.1.0", features = ["serde"]}
console_error_panic_hook = "0.1.7"
once_cell = "1.14.0"
semver = "1.0.13"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_derive = "1.0.144"
log = "0.4.17"
toml = "0.5.9"
paste = "1.0.9"
anyhow = "1.0.64"
thiserror = "1.0.34"
maplit = "1.0.2"
web-sys = {version = "0.3.59", features = ["console"]}
