[package]
name = "marine-js"
version = "0.3.0"
edition = "2018"
description = "Web version of the marine runtime"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
marine-it-interfaces = { path = "../crates/it-interfaces", version = "0.7.1" }
marine-module-interface = { path = "../crates/module-interface", version = "0.4.1" }
marine-utils = { path = "../crates/utils", version = "0.4.0" }
marine-min-it-version =  { path = "../crates/min-it-version", version = "0.1.0"}
it-json-serde = { path = "../crates/it-json-serde", version = "0.3.1" }

marine-rs-sdk = "0.6.15"
wasmer-it = { package = "wasmer-interface-types-fl", version = "0.23.1" }
fluence-it-types = {version = "0.3.1", features = ["impls"] }
it-lilo = "0.4.0"
it-memory-traits = "0.3.0"

wasm-bindgen = "0.2"
nom = "5.1"
itertools = "0.10.1"
multimap = "0.8.1"
boolinator = "2.4.0"
bytesize = {version = "1.1.0", features = ["serde"]}
console_error_panic_hook = "0.1.7"
once_cell = "1.7.2"
semver = "0.11.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.53"
serde_derive = "1.0.118"
serde_with = "1.11.0"
log = "0.4.8"
toml = "0.5.8"
paste = "1.0.5"
anyhow = "1.0.31"
thiserror = "1.0.24"
maplit = "1.0.2"
web-sys = {version = "0.3.56", features = ["console"]}
