name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot-*.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  marine:
    uses: ./.github/workflows/snapshot-cargo.yml
    with:
      ref: ${{ github.ref }}

  marine-js:
    name: "marine"
    uses: ./.github/workflows/snapshot-marine-js.yml
    with:
      ref: ${{ github.ref }}

  marine-rs-sdk-test:
    needs:
      - marine

    uses: fluencelabs/marine-rs-sdk-test/.github/workflows/tests.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-app-service",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-app-service",
            "manifest": "crates/marine-test-macro-impl/Cargo.toml",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          }
        ]

  aquavm-wasm:
    name: "aquavm"
    needs:
      - marine

    uses: fluencelabs/aquavm/.github/workflows/snapshot-air-iterpreter-wasm.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "marine-runtime",
            "manifest": "avm/server/Cargo.toml",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-app-service",
            "manifest": "air/Cargo.toml",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          }
        ]

  aquavm-crates:
    needs:
      - aquavm-wasm

    uses: fluencelabs/aquavm/.github/workflows/snapshot-cargo.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "marine-runtime",
            "manifest": "avm/server/Cargo.toml",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-app-service",
            "manifest": "air/Cargo.toml",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          }
        ]

  aquavm-avm:
    needs:
      - aquavm-wasm
    uses: fluencelabs/aquavm/.github/workflows/snapshot-avm.yml@master

  rust-peer:
    needs:
      - marine
      - aquavm-crates

    uses: fluencelabs/rust-peer/.github/workflows/build.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-app-service",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          },
          {
            "package": "avm-server",
            "version": "=${{ needs.aquavm-crates.outputs.version }}",
            "registry": "fluence"
          },
          {
            "package": "air-interpreter-wasm",
            "version": "=${{ needs.aquavm-crates.outputs.version }}",
            "registry": "fluence"
          }
        ]

  rust-peer-snapshot:
    needs:
      - rust-peer

    uses: fluencelabs/rust-peer/.github/workflows/snapshot.yml@master
    with:
      image-name: "docker.fluence.dev/marine"
      flavour: "minimal"

  rust-peer-tests:
    name: "rust-peer"
    needs:
      - marine
      - aquavm

    uses: fluencelabs/rust-peer/.github/workflows/tests.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-app-service",
            "version": "=${{ needs.marine.outputs.version }}",
            "registry": "fluence"
          },
          {
            "package": "avm-server",
            "version": "=${{ needs.aquavm-crates.outputs.version }}",
            "registry": "fluence"
          },
          {
            "package": "air-interpreter-wasm",
            "version": "=${{ needs.aquavm.outputs.version }}",
            "registry": "fluence"
          }
        ]

  js-client-tests:
    name: "js-client"
    needs:
      - marine-js
      - aquavm-avm
      - rust-peer-snapshot

    uses: fluencelabs/js-client/.github/workflows/tests.yml@master
    with:
      marine-js-version: "${{ needs.marine-js.outputs.version }}"
      avm-version: "${{ needs.aquavm-avm.outputs.version }}"
      rust-peer-image: "${{ needs.rust-peer-snapshot.outputs.rust-peer-image }}"

  js-client:
    needs:
      - marine
      - aquavm-avm

    uses: fluencelabs/js-client/.github/workflows/snapshot.yml@master
    with:
      marine-js-version: "${{ needs.marine-jq.outputs.version }}"
      avm-version: "${{ needs.aquavm-avm.outputs.version }}"

  aqua-playground:
    needs:
      - js-client
      - rust-peer-snapshot

    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      js-client-snapshots: "${{ needs.js-client.outputs.js-client-snapshots }}"
      rust-peer-image: "${{ needs.rust-peer-snapshot.outputs.rust-peer-image }}"

  registry:
    needs:
      - rust-peer

    uses: fluencelabs/registry/.github/workflows/tests.yml@main
    with:
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"

  fluence-cli:
    needs:
      - marine
      - rust-peer

    uses: fluencelabs/fluence-cli/.github/workflows/tests.yml@main
    with:
      marine-version: "${{ needs.marine.outputs.cargo-version }}"
      mrepl-version: "${{ needs.marine.outputs.cargo-version }}"
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"

  status:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - fluence-cli
      - registry
      - aqua-playground

    steps:
      - uses: lwhiteley/dependent-jobs-result-check@v1
        id: status
        with:
          statuses: failure,cancelled,skipped
          dependencies: ${{ toJSON(needs) }}

      - name: Log output
        run: |
          echo "statuses:" "${{ steps.status.outputs.statuses }}"
          echo "jobs:" "${{ steps.status.outputs.jobs }}"
          echo "found any?:" "${{ steps.status.outputs.found }}"

      - name: Fail run
        if: fromJSON(steps.status.outputs.found)
        run: exit 1
