name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: true

jobs:
  snapshot:
    name: "marine"
    uses: ./.github/workflows/snapshot.yml

  aquavm:
    needs:
      - snapshot

    uses: fluencelabs/aquavm/.github/workflows/snapshot.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "marine-runtime",
            "manifest": "avm/server/Cargo.toml",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-app-service",
            "manifest": "air/Cargo.toml",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]

  rust-peer:
    needs:
      - snapshot
      - aquavm

    uses: fluencelabs/rust-peer/.github/workflows/snapshot.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-app-service",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "avm-server",
            "version": "=${{ needs.aquavm.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "air-interpreter-wasm",
            "version": "=${{ needs.aquavm.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]

  fluence-js-tests:
    name: "fluence-js"
    needs:
      - aquavm
      - rust-peer

    uses: fluencelabs/fluence-js/.github/workflows/tests.yml@master
    with:
      avm-version: "${{ needs.aquavm.outputs.avm-version }}"
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"

  fluence-js-snapshot:
    name: "fluence-js"
    needs:
      - aquavm

    uses: fluencelabs/fluence-js/.github/workflows/snapshot.yml@master
    with:
      avm-version: "${{ needs.aquavm.outputs.avm-version }}"

  aqua-snapshot:
    name: "aqua"
    needs:
      - fluence-js-snapshot

    uses: fluencelabs/aqua/.github/workflows/snapshot.yml@main
    with:
      fluence-js-version: "${{ needs.fluence-js-snapshot.outputs.fluence-js-version }}"

  aqua-playground:
    needs:
      - fluence-js-snapshot
      - aqua-snapshot
      - rust-peer

    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      fluence-js-version: "${{ needs.fluence-js-snapshot.outputs.fluence-js-version }}"
      aqua-version: "${{ needs.aqua-snapshot.outputs.aqua-version }}"
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"

  registry:
    needs:
      - aqua-snapshot
      - rust-peer

    uses: fluencelabs/registry/.github/workflows/tests.yml@main
    with:
      aqua-version: "${{ needs.aqua-snapshot.outputs.aqua-version }}"
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"
