name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: true

jobs:
  marine-rs-sdk-test:
    uses: fluencelabs/marine-rs-sdk-test/.github/workflows/tests.yml@marine-e2e
    with:
      fluence-app-service-version: |
        {
          "git": "https://github.com/fluencelabs/marine",
          "branch": "${{ github.head_ref }}"
        }

  aquavm:
    uses: fluencelabs/aquavm/.github/workflows/snapshot@marine-e2e
    with:
      marine-runtime-version: |
        {
          "git": "https://github.com/fluencelabs/marine",
          "branch": "${{ github.head_ref }}"
        }

  rust-peer:
    needs:
      - aquavm

    uses: fluencelabs/rust-peer/.github/workflows/snapshot@master
    with:
      fluence-app-service-version: |
        {
          "git": "https://github.com/fluencelabs/marine",
          "branch": "${{ github.head_ref }}"
        }
      avm-server-version: |
        {
          "version": "=${{ needs.aquavm.outputs.avm-server-version }}",
          "registry": "fluence"
        }
