name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: true

jobs:
  marine-rs-sdk-test:
    uses: fluencelabs/marine-rs-sdk-test/.github/workflows/tests.yml@marine-e2e
    with:
      fluence-app-service-version: |
        {
          "git": "https://github.com/fluencelabs/marine",
          "branch": "${{ github.head_ref }}"
        }
