name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: true

jobs:
  snapshot:
    name: "marine"
    uses: ./.github/workflows/snapshot.yml

  aquavm:
    needs:
      - snapshot

    uses: fluencelabs/aquavm/.github/workflows/snapshot.yml@marine-e2e
    with:
      cargo-dependencies: |
        [
          {
            "package": "marine-runtime",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-app-service",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]
