[package]
name = "consumer"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = { workspace = true }
publish = false

[[bin]]
name = "consumer"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.0"
