[package]
name = "fluence-app-service"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
fluence-faas = { path = "../fluence-faas" }

toml = "0.5.6"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
serde_derive = "1.0.111"
cmd_lib = "0.7.8"
log = "0.4.8"

[features]
raw-module-api = ["fluence-faas/raw-module-api"]
